# Generated by Django 5.0.14 on 2025-11-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('business_owner_it', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ART',
                'verbose_name_plural': 'ARTs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_url', models.URLField(max_length=500)),
                ('model_name', models.CharField(max_length=200)),
                ('auth_token_env_var', models.CharField(help_text='Environment variable name for auth token', max_length=100)),
                ('timeout_s', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KI Provider',
                'verbose_name_plural': 'KI Providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('category', models.CharField(choices=[('techstack', 'Techstack'), ('fachlichkeit', 'Fachlichkeit'), ('hexagonal', 'Hexagonale Architektur'), ('rest_l2', 'REST Level 2'), ('security', 'Security'), ('performance', 'Performance'), ('other', 'Sonstiges')], default='other', max_length=50)),
                ('prompt_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('alphabet_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='persistence.art')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_download_root', models.CharField(default='/data/repos', max_length=500)),
                ('include_patterns', models.TextField(default='*.py,*.md,*.txt,*.js,*.ts')),
                ('exclude_paths', models.TextField(default='.git,node_modules,dist,build,target,venv,.venv')),
                ('max_concat_bytes', models.IntegerField(default=460800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_ki_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='persistence.kiprovider')),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('tech_stack', models.TextField(blank=True)),
                ('namespace_path', models.CharField(blank=True, max_length=500)),
                ('visibility', models.CharField(default='internal', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='persistence.application')),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField()),
                ('response_json', models.JSONField()),
                ('score_pct', models.IntegerField(blank=True, help_text='Score 0-100', null=True)),
                ('summary', models.TextField(blank=True)),
                ('improvement_suggestions', models.JSONField(blank=True, default=dict)),
                ('endpoints', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ki_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='persistence.kiprovider')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='persistence.prompt')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_runs', to='persistence.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarkdownCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_bytes', models.IntegerField()),
                ('file_count', models.IntegerField()),
                ('is_complete', models.BooleanField(default=True, help_text='False if size limit was reached')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markdown_corpora', to='persistence.repository')),
            ],
            options={
                'verbose_name_plural': 'Markdown Corpora',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['external_id', 'is_active'], name='persistence_externa_29dfb2_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['namespace_path'], name='persistence_namespa_d88e17_idx'),
        ),
        migrations.AddIndex(
            model_name='promptrun',
            index=models.Index(fields=['repository', 'prompt', '-created_at'], name='persistence_reposit_10e471_idx'),
        ),
    ]
