# Generated by Django 5.0.14 on 2025-11-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as important repository'),
        ),
    ]
