# Generated by Django 5.0.14 on 2025-11-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_repository_is_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(choices=[('REST', 'REST API'), ('SOAP', 'SOAP Service')], max_length=10)),
                ('url', models.CharField(help_text='URL path or WSDL URL', max_length=1000)),
                ('http_method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], help_text='HTTP method (REST only)', max_length=10, null=True)),
                ('operation_name', models.CharField(blank=True, help_text='Operation name (SOAP only)', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True, help_text='Quality assessment of this endpoint')),
                ('target_maturity_level', models.IntegerField(default=2, help_text='Target maturity level (e.g., 2 for REST Level 2)')),
                ('actual_maturity_level', models.IntegerField(blank=True, help_text='Actual achieved maturity level (0-3 for REST)', null=True)),
                ('maturity_score_pct', models.IntegerField(blank=True, help_text='How well target is met (0-100%)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_endpoints', to='persistence.promptrun')),
            ],
            options={
                'ordering': ['-created_at', 'url'],
            },
        ),
        migrations.CreateModel(
            name='QualityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('BDD', 'Behavior Driven Development'), ('SECURITY', 'Security Analysis'), ('HEXAGONAL', 'Hexagonal Architecture'), ('PERFORMANCE', 'Performance Analysis'), ('REST', 'REST API Quality'), ('SOAP', 'SOAP Service Quality'), ('TESTING', 'Test Coverage & Quality'), ('DOCUMENTATION', 'Documentation Quality'), ('CODE_QUALITY', 'Code Quality'), ('OTHER', 'Other')], max_length=20)),
                ('score_pct', models.IntegerField(help_text='Overall score 0-100')),
                ('assessment_text', models.TextField(help_text='Detailed assessment description')),
                ('advantages', models.JSONField(blank=True, default=list, help_text='List of identified advantages')),
                ('improvement_suggestions', models.JSONField(blank=True, default=list, help_text='List of improvement suggestions with effort')),
                ('effort_estimate_days', models.DecimalField(blank=True, decimal_places=1, help_text='Total effort estimate in person-days', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_analyses', to='persistence.promptrun')),
            ],
            options={
                'verbose_name_plural': 'Quality Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceendpoint',
            index=models.Index(fields=['prompt_run', 'endpoint_type'], name='persistence_prompt__25b7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceendpoint',
            index=models.Index(fields=['endpoint_type', '-created_at'], name='persistence_endpoin_01e7e2_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityanalysis',
            index=models.Index(fields=['prompt_run', 'analysis_type'], name='persistence_prompt__8c3e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityanalysis',
            index=models.Index(fields=['analysis_type', '-created_at'], name='persistence_analysi_f50621_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityanalysis',
            index=models.Index(fields=['score_pct'], name='persistence_score_p_1a9c82_idx'),
        ),
    ]
